"""name unique in character

Revision ID: 97bcd96bdca0
Revises: 1871434c18d9
Create Date: 2024-01-13 13:51:50.082310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97bcd96bdca0'
down_revision: Union[str, None] = '1871434c18d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'characters', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='unique')
    # ### end Alembic commands ###
